name: CI

on:
  pull_request:
    branches:
      - main
  push:
    branches:
      - main
  workflow_dispatch:

permissions:
  contents: read

jobs:
  rust:
    name: Rust
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v6.0.3
        with:
          fetch-depth: 0

      - name: Install Rust
        run: rustup toolchain install 1.94.1 --profile minimal --component clippy rustfmt

      - name: Use Rust 1.94.1
        run: rustup default 1.94.1

      - name: Cache Rust
        uses: Swatinem/rust-cache@v2.9.1

      - name: Check formatting
        run: cargo fmt --check

      - name: Test
        run: cargo test --locked

      - name: Clippy
        run: cargo clippy --all-targets --locked -- -D warnings

  changesets:
    name: Changesets
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v6.0.3

      - name: Setup Node
        uses: actions/setup-node@v6.4.0
        with:
          node-version: 25.9.0
          cache: npm

      - name: Install Node dependencies
        run: npm ci

      - name: Check Changesets
        run: npx changeset status --since=origin/main
        if: github.event_name == 'pull_request'
